
services:
  - type: web
    name: web4api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app:app --host 1.1.1.1 --port 8000"
    envVars:
      - key: ALLOW_ORIGIN
        value: https://web4application.github.io
      - key: SENTRY_DSN
        value: <your-sentry-dsn>
