name: Web4AI Enhance
description: Refactor, comment, and document code using AI

inputs:
  node-version:
    description: Node.js version to use
    required: false
    default: '18'

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install dependencies
      run: |
        if [ -f package-lock.json ]; then
          npm ci
        else
          echo "⚠️ package-lock.json missing — running npm install"
          npm install
        fi

   - name: Generate changelog summary
     run: node changelog.js
     id: changelog

      shell: bash

    - name: Run Web4AI Enhancer
      run: node backend/runAITasks.js
      shell: bash

    - name: Commit enhanced code
      run: |
        git config --global user.name 'Web4AI Bot'
        git config --global user.email 'bot@web4ai.dev'
        git add .
        git commit -m "🔁 AI-enhanced: refactor, comments, docs"
        git push
      shell: bash

outputs:
  changelog:
    description: Summary of changes generated by Web4AI
    value: ${{ steps.changelog.outputs.summary }}

